### PR TITLE
Initial method of reading NIFTI files

### PR DESCRIPTION
**Pull request by mfalkiewicz**
This function will read in the NIFTI data and preprocess it, if needed.

---
This change is [Reviewable](https://reviewable.io/reviews/kjurek/py-total-activation/13)

### CODE REVIEW

**Comment by kjurek** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[TotalActivationTool.py, line 56 at r3](https://reviewable.io:443/reviews/kjurek/py-total-activation/13#-KhbKO_2XY_e--qwgizJ:-KhbKO_2XY_e--qwgizK:b-8dpz2y) ([raw file](https://github.com/kjurek/py-total-activation/blob/644265c3fbfffab881b3a3d327c14428e8435fc9/TotalActivationTool.py#L56)):*
> self.voxels
I would rename it to n_voxels or voxels_count

---

*[TotalActivationTool.py, line 58 at r3](https://reviewable.io:443/reviews/kjurek/py-total-activation/13#-KhbKm8GLjmn4jrNgEd0:-KhbKm8GLjmn4jrNgEd1:bguto07) ([raw file](https://github.com/kjurek/py-total-activation/blob/644265c3fbfffab881b3a3d327c14428e8435fc9/TotalActivationTool.py#L58)):*
> Voxels.shape
same here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kjurek/py-total-activation/13)*

**Comment by kjurek** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kjurek/py-total-activation/13)*

**Comment by mfalkiewicz** [comment]
This should work properly now. This reads in 132 voxels from the test data and stores them as a time x space matrix. It also stores the relevant voxels for the atlas. The nice thing is that we can always transform the data back into the original image, because the masker objects are stored.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/kjurek/py-total-activation/13#-:-KhbR1Rz66LETf6rroy7:b-wkzsmm)*

**Comment by mfalkiewicz** [comment]
*[TotalActivationTool.py, line 56 at r3](https://reviewable.io:443/reviews/kjurek/py-total-activation/13#-KhbKO_2XY_e--qwgizJ:-KhbR_5oHQlKu-Ow9g7H:b-896fix) ([raw file](https://github.com/kjurek/py-total-activation/blob/644265c3fbfffab881b3a3d327c14428e8435fc9/TotalActivationTool.py#L56)):*
<details><summary><i>Previously, kjurek wrote…</i></summary><blockquote>

> self.voxels
I would rename it to n_voxels or voxels_count
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kjurek/py-total-activation/13)*

**Comment by mfalkiewicz** [comment]
*[TotalActivationTool.py, line 58 at r3](https://reviewable.io:443/reviews/kjurek/py-total-activation/13#-KhbKm8GLjmn4jrNgEd0:-KhbRZQv13jkCDcdLJCU:b-896fix) ([raw file](https://github.com/kjurek/py-total-activation/blob/644265c3fbfffab881b3a3d327c14428e8435fc9/TotalActivationTool.py#L58)):*
<details><summary><i>Previously, kjurek wrote…</i></summary><blockquote>

> Voxels.shape
same here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kjurek/py-total-activation/13)*

**Comment by kjurek** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kjurek/py-total-activation/13)*

**Pull request merged**
